version: '3.1'
services:
  db:
    container_name: psql_db
    image: postgres:12
    environment:
      POSTGRES_USER: jorgepl
      POSTGRES_PASSWORD: admin
    ports:
      - 5677:5432
    volumes: 
      - ./scripts:/scripts